import Head from 'next/head';
import { FiSearch } from 'react-icons/fi';
import Navbar from '../components/Navbar';
import Recommended from '../components/Recommended';
import SearchBar from '../components/SearchBar';
import Trending from '../components/Trending';

export default function Home() {
  return (
    <>
      <Head>
        <title>PopCorn Time</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
      <div className="md:ml-24">
        <div className="max-w-[450px] md:max-w-full mx-auto mt-8">
          <div className="flex items-center">
            <div className="mr-4 text-2xl">
              <FiSearch />
            </div>
            <div className="w-full">
              <SearchBar />
            </div>
          </div>
        </div>
        <Trending />
        <Recommended />
      </div>
    </>
  );
}
