import { data } from 'autoprefixer';
import Head from 'next/head';
import { useState } from 'react';
import Recommended from '../components/Recommended';
import SearchBar from '../components/SearchBar';
import Trending from '../components/Trending';

export default function Home() {
  return (
    <>
      <Head>
        <title>PopCorn Time</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        <SearchBar />
        <Trending />
        <Recommended />
      </div>
    </>
  );
}
